// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"database/sql"
	"time"
)

type Task struct {
	ID         interface{}
	Type       interface{}
	ProcessID  interface{}
	LogPath    interface{}
	Status     string
	Retries    int64
	MaxRetries int64
	WorkerID   sql.NullInt64
	Error      interface{}
	CreatedAt  time.Time
	UpdatedAt  time.Time
	StartedAt  sql.NullTime
	FinishedAt sql.NullTime
}
